#spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#oracle.jdbc.fanEnabled=false
##this is not used when deployed in kubernetes. Just for local testing
spring.datasource.url=jdbc:oracle:thin:@s2a6t4xnlbjjgivs_high?TNS_ADMIN=/Users/santigutierrezgonzalez/Documents/Programacion/6TO-Semestre/OCI-Project/wallet/Wallet
spring.datasource.username=ADMIN
spring.datasource.password=$ique$iDatabase2024

##Properties of UCP
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

##Logging properties for UCP
logging.level.root=trace
logging.file.name=logs.log
logging.level.oracle.ucp=trace

#spring.security.user.name=psong
#spring.security.user.password=WELcome__12345

telegram.bot.token=7564059515:AAFrLbbDMtpXYF8DiYw1ocS5GuNCPsqg3Ro
telegram.bot.name=javjul_bot


# optional, this changes the port of the development server
# set to whatever you need
server.port=8081
openai.api.key=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
#openai.api.key=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