apiVersion: apps/v1
kind: Deployment
metadata:
  name: ToDoListApp
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: ToDoListApp
  template:
    metadata:
      labels:
        app: ToDoListApp
    spec:
      containers:
      - name: ToDoListApp
        image: <region-code>.ocir.io/<tenancy-name>/<repo-name>:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: ToDoListApp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ToDoListApp